global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "kv-store-cluster"
    static_configs:
      - targets: ["kv-store-1:16700", "kv-store-2:16700", "kv-store-3:16700"]
  - job_name: "raft-monitoring"
    static_configs:
      - targets: ["kv-store-1:16901", "kv-store-2:16902", "kv-store-3:16903"]
